Wip/9838 error reporting concept
ChimeraTK/ControlSystemAdapter pull request #43
Opened 2022-06-10 13:28 UTC by d-rothe

consider same branch of ApplicationCore, ControlSystemAdapter and DoocsAdapter

2022-06-13 14:05 UTC, mhier requested changes
I think this mixes two independent changes. I approve them both, but I think they should go into separate PRs / commits in the master. Other than this I have only cosmetic comments.

2022-06-13 14:44 UTC, d-rothe commented on include/ChimeraTK/ControlSystemAdapter/ControlSystemPVManager.h
> +     * the specified name. Throws a logic_error if there is a process
it is related because the unit test I wrote for error reporting in DoocsAdapter was failing due to this problem

2022-06-13 14:48 UTC, d-rothe commented on include/ChimeraTK/ControlSystemAdapter/PVManager.h
> +    bool hasProcessArray(ChimeraTK::RegisterPath const& processVariableName) const;
see above

2022-06-13 14:48 UTC, d-rothe commented on include/ChimeraTK/ControlSystemAdapter/StatusWithMessageReader.h
> +  /// only for code deduplication, not for direct use
done

2022-06-13 14:48 UTC, d-rothe commented on include/ChimeraTK/ControlSystemAdapter/StatusWithMessageReader.h
> +        return false;
done

2022-06-15 08:18 UTC, mhier approved these changes
Just don't squash the unrelated changes into one commit. Make sure you have two commits or so (i.e. hide the detours).

2022-06-15 09:16 UTC, merged